# Initially generated by Pyright

from abc import ABCMeta, abstractmethod
from typing import Literal

from . import PrometheusMetrics

class MultiprocessPrometheusMetrics(PrometheusMetrics):
    __metaclass__ = ABCMeta

    @abstractmethod
    def should_start_http_server(self) -> bool: ...

class GunicornPrometheusMetrics(MultiprocessPrometheusMetrics):
    def should_start_http_server(self) -> Literal[True]: ...
    @classmethod
    def start_http_server_when_ready(cls, port: int, host: str = ...) -> None: ...
    @classmethod
    def mark_process_dead_on_child_exit(cls, pid: int) -> None: ...
