# Initially generated by Pyright
#
import pathlib

def run(
    tailwindcss_cli_args: list[str] | str = ...,
    cwd: pathlib.Path | str = ...,
    bin_path: pathlib.Path | str = ...,
    env: dict[str, str] = ...,
    live_output: bool = ...,
    auto_install: bool = ...,
    version: str = ...,
) -> str: ...
