# Initially generated by Pyright

import io

def jsmin(js: str, **kwargs: object) -> str: ...

class JavascriptMinify:
    def __init__(
        self,
        instream: io.StringIO = ...,
        outstream: io.StringIO = ...,
        quote_chars: str = ...,
    ) -> None: ...
    def minify(
        self, instream: io.StringIO = ..., outstream: io.StringIO = ...
    ) -> None: ...
