# Initially generated by Pyright

import datetime

import pandas as pd
import requests

class TickerBase:
    def __init__(
        self,
        ticker: str | tuple[str, str],
        session: requests.Session | None = ...,
    ) -> None: ...
    def history(
        self,
        period: str | None = ...,
        interval: str = ...,
        start: datetime.date | str | None = ...,
        end: datetime.date | str | None = ...,
        prepost: bool = ...,
        actions: bool = ...,
        auto_adjust: bool = ...,
        back_adjust: bool = ...,
        repair: bool = ...,
        keepna: bool = ...,
        rounding: bool = ...,
        timeout: float | None = ...,
        raise_errors: bool = ...,
    ) -> pd.DataFrame: ...
