# Initially generated by Pyright

from typing import NotRequired, TypedDict

import requests

from .base import TickerBase
from .scrapers.funds import FundsData

class Info(TypedDict):

    currency: str
    sector: NotRequired[str | None]

class Ticker(TickerBase):
    def __init__(
        self,
        ticker: str | tuple[str, str],
        session: requests.Session | None = ...,
    ) -> None: ...
    @property
    def info(self) -> Info: ...
    @property
    def funds_data(self) -> FundsData: ...
