# Initially generated by Pyright

from decimal import Decimal
from typing import overload

from _pytest import __version__, version_tuple
from _pytest._code import ExceptionInfo
from _pytest.assertion import register_assert_rewrite
from _pytest.cacheprovider import Cache
from _pytest.capture import CaptureFixture
from _pytest.config import (
    cmdline,
    Config,
    console_main,
    ExitCode,
    hookimpl,
    hookspec,
    main,
    PytestPluginManager,
    UsageError,
)
from _pytest.config.argparsing import OptionGroup, Parser
from _pytest.doctest import DoctestItem
from _pytest.fixtures import (
    fixture,
    FixtureDef,
    FixtureLookupError,
    FixtureRequest,
)
from _pytest.freeze_support import freeze_includes
from _pytest.legacypath import TempdirFactory, Testdir
from _pytest.logging import LogCaptureFixture
from _pytest.main import Dir, Session
from _pytest.mark import HIDDEN_PARAM, Mark
from _pytest.mark import MARK_GEN as mark
from _pytest.mark import MarkDecorator, MarkGenerator, param
from _pytest.monkeypatch import MonkeyPatch
from _pytest.nodes import Collector, Directory, File, Item
from _pytest.outcomes import exit, fail, importorskip, skip, xfail
from _pytest.pytester import (
    HookRecorder,
    LineMatcher,
    Pytester,
    RecordedHookCall,
    RunResult,
)
from _pytest.python import Class, Function, Metafunc, Module, Package
from _pytest.python_api import ApproxBase, ApproxDecimal, ApproxScalar
from _pytest.raises import raises, RaisesExc, RaisesGroup
from _pytest.recwarn import deprecated_call, WarningsRecorder, warns
from _pytest.reports import CollectReport, TestReport
from _pytest.runner import CallInfo
from _pytest.stash import Stash, StashKey
from _pytest.subtests import SubtestReport, Subtests
from _pytest.terminal import TerminalReporter, TestShortLogReport
from _pytest.tmpdir import TempPathFactory
from _pytest.warning_types import (
    PytestAssertRewriteWarning,
    PytestCacheWarning,
    PytestCollectionWarning,
    PytestConfigWarning,
    PytestDeprecationWarning,
    PytestExperimentalApiWarning,
    PytestFDWarning,
    PytestRemovedIn9Warning,
    PytestRemovedIn10Warning,
    PytestReturnNotNoneWarning,
    PytestUnhandledThreadExceptionWarning,
    PytestUnknownMarkWarning,
    PytestUnraisableExceptionWarning,
    PytestWarning,
)

@overload
def approx[T: Decimal](
    expected: T,
    rel: T | None = None,
    abs: T | None = None,
    nan_ok: bool = False,
) -> ApproxDecimal: ...
@overload
def approx[T](
    expected: T,
    rel: T | None = None,
    abs: T | None = None,
    nan_ok: bool = False,
) -> ApproxScalar: ...
def approx[T](
    expected: T,
    rel: T | None = None,
    abs: T | None = None,
    nan_ok: bool = False,
) -> ApproxBase: ...

__all__ = [
    "HIDDEN_PARAM",
    "Cache",
    "CallInfo",
    "CaptureFixture",
    "Class",
    "CollectReport",
    "Collector",
    "Config",
    "Dir",
    "Directory",
    "DoctestItem",
    "ExceptionInfo",
    "ExitCode",
    "File",
    "FixtureDef",
    "FixtureLookupError",
    "FixtureRequest",
    "Function",
    "HookRecorder",
    "Item",
    "LineMatcher",
    "LogCaptureFixture",
    "Mark",
    "MarkDecorator",
    "MarkGenerator",
    "Metafunc",
    "Module",
    "MonkeyPatch",
    "OptionGroup",
    "Package",
    "Parser",
    "PytestAssertRewriteWarning",
    "PytestCacheWarning",
    "PytestCollectionWarning",
    "PytestConfigWarning",
    "PytestDeprecationWarning",
    "PytestExperimentalApiWarning",
    "PytestFDWarning",
    "PytestPluginManager",
    "PytestRemovedIn9Warning",
    "PytestRemovedIn10Warning",
    "PytestReturnNotNoneWarning",
    "PytestUnhandledThreadExceptionWarning",
    "PytestUnknownMarkWarning",
    "PytestUnraisableExceptionWarning",
    "PytestWarning",
    "Pytester",
    "RaisesExc",
    "RaisesGroup",
    "RecordedHookCall",
    "RunResult",
    "Session",
    "Stash",
    "StashKey",
    "SubtestReport",
    "Subtests",
    "TempPathFactory",
    "TempdirFactory",
    "TerminalReporter",
    "TestReport",
    "TestShortLogReport",
    "Testdir",
    "UsageError",
    "WarningsRecorder",
    "__version__",
    "approx",
    "cmdline",
    "console_main",
    "deprecated_call",
    "exit",
    "fail",
    "fixture",
    "freeze_includes",
    "hookimpl",
    "hookspec",
    "importorskip",
    "main",
    "mark",
    "param",
    "raises",
    "register_assert_rewrite",
    "skip",
    "version_tuple",
    "warns",
    "xfail",
]
