# Initially generated by Pyright

from collections.abc import Callable

import flask

from .mixins import AnonymousUserMixin, UserMixin

class LoginManager:
    login_view: str | None
    def __init__(
        self,
        app: flask.Flask = ...,
        add_context_processor: bool = ...,
    ) -> None: ...
    def setup_app(
        self,
        app: flask.Flask,
        add_context_processor: bool = ...,
    ) -> None: ...
    def init_app(self, app: flask.Flask, add_context_processor: bool = ...) -> None: ...
    def unauthorized(self) -> flask.Response: ...
    def user_loader(
        self,
        callback: Callable[[str], UserMixin | AnonymousUserMixin | None],
    ) -> None: ...
    @property
    def user_callback(self) -> None: ...
    def request_loader(
        self,
        callback: Callable[[flask.Request], UserMixin | AnonymousUserMixin | None],
    ) -> None: ...
    @property
    def request_callback(self) -> None: ...
    def unauthorized_handler[T: Callable[[], flask.Response]](
        self,
        callback: T,
    ) -> T: ...
    def needs_refresh_handler[T: Callable[[], flask.Response]](
        self,
        callback: T,
    ) -> T: ...
    def needs_refresh(self) -> flask.Response: ...
    def header_loader[T: Callable[[str], UserMixin | AnonymousUserMixin | None]](
        self,
        callback: T,
    ) -> T: ...
