# Initially generated by Pyright

from typing import overload

from Cryptodome.Cipher._mode_cbc import CbcMode
from typing_extensions import Literal

Buffer = bytes | bytearray | memoryview
MODE_ECB: Literal[1]
MODE_CBC: Literal[2]
MODE_CFB: Literal[3]
MODE_OFB: Literal[5]
MODE_CTR: Literal[6]
MODE_OPENPGP: Literal[7]
MODE_CCM: Literal[8]
MODE_EAX: Literal[9]
MODE_SIV: Literal[10]
MODE_GCM: Literal[11]
MODE_OCB: Literal[12]

@overload
def new(key: Buffer, mode: Literal[1], use_aesni: bool = ...) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[2], iv: Buffer | None = ..., use_aesni: bool = ...
) -> CbcMode: ...
@overload
def new(
    key: Buffer, mode: Literal[2], IV: Buffer | None = ..., use_aesni: bool = ...
) -> CbcMode: ...
@overload
def new(
    key: Buffer,
    mode: Literal[3],
    iv: Buffer | None = ...,
    segment_size: int = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[3],
    IV: Buffer | None = ...,
    segment_size: int = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[5], iv: Buffer | None = ..., use_aesni: bool = ...
) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[5], IV: Buffer | None = ..., use_aesni: bool = ...
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[6],
    nonce: Buffer | None = ...,
    initial_value: Buffer | int = ...,
    counter: dict[object, object] = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[7], iv: Buffer | None = ..., use_aesni: bool = ...
) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[7], IV: Buffer | None = ..., use_aesni: bool = ...
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[8],
    nonce: Buffer | None = ...,
    mac_len: int = ...,
    assoc_len: int = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[9],
    nonce: Buffer | None = ...,
    mac_len: int = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer, mode: Literal[10], nonce: Buffer | None = ..., use_aesni: bool = ...
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[11],
    nonce: Buffer | None = ...,
    mac_len: int = ...,
    use_aesni: bool = ...,
) -> None: ...
@overload
def new(
    key: Buffer,
    mode: Literal[12],
    nonce: Buffer | None = ...,
    mac_len: int = ...,
    use_aesni: bool = ...,
) -> None: ...

block_size: int
key_size: tuple[int, int, int]
