name: Deploy
on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:
  # pypy-publish:
  #   name: Upload release to PyPi
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/nummus-financial
  #   permissions:
  #     id-token: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.release.tag_name }}
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.13"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install .[build]
  #     - name: Build package
  #       run: python -m build
  #     - name: Publish package
  #       uses: pypa/gh-action-pypi-publish@v1.12.4
  docker-publish:
    name: Upload release to Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: docker
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[build-docker]
      - name: Build python package
        run: |
          echo "PY_VERSION=$(python -m setuptools_scm)" >> $GITHUB_ENV
          python -m build --wheel --outdir /tmp
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: wattsup/nummus-financial:latest
          build-args: "WHL=/tmp/nummus_financial-${{ env.PY_VERSION }}-py3-none-any.whl"
